version: 2
jobs:
  api-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t falcontext_api:0.1 ./api/

workflows:
  version: 2
  api_build&deploy:
    jobs:
      - api-build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^api_v[0-9]+(\.[0-9]+)*$/
