version: 2
jobs:
  api-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docke_layer_caching: true
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=API-0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=falcontext' >> $BASH_ENV 
      - run: 
          name: Build Docker image 
          command: |
            docker build -t falcontext_api:0.1 ./api/
      - run:
          name: Publish Docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push andreichirita92/$IMAGE_NAME:$TAG


workflows:
  version: 2
  api_build&deploy:
    jobs:
      - api-build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^api_v[0-9]+(\.[0-9]+)*$/
